# Базовый образ: Node.js для разработки
FROM node:20-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json из frontend/ (относительно контекста)
COPY frontend/package*.json ./

# Устанавливаем зависимости (включая devDependencies для TypeScript и Webpack)
RUN npm install

# Копируем весь код из frontend/
COPY frontend/ ./

# Экспонируем порт (предположим 3000 для webpack-dev-server)
EXPOSE 3000

# Запускаем dev-сервер

CMD ["npm", "run", "start"]